# Generated by Django 4.2.13 on 2024-06-21 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("davo", "0002_sensor_1_sensor_2_sensordata_2_sensordata_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata_1",
            name="sensor",
        ),
        migrations.RemoveField(
            model_name="sensordata_2",
            name="sensor",
        ),
        migrations.DeleteModel(
            name="Sensor_1",
        ),
        migrations.DeleteModel(
            name="Sensor_2",
        ),
    ]
