# Generated by Django 4.2.13 on 2024-06-21 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("davo", "0003_remove_sensordata_1_sensor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata_1",
            name="battery_level",
        ),
    ]
