# Generated by Django 4.2.13 on 2024-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("davo", "0005_sensordata_1_battery_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="P_command_SensorData_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battery_level", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_25", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_50", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_75", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "electrical_conductivity",
                    models.DecimalField(decimal_places=1, max_digits=2),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="P_command_SensorData_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battery_level", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_25", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_50", models.DecimalField(decimal_places=1, max_digits=3)),
                ("humidity_75", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "electrical_conductivity",
                    models.DecimalField(decimal_places=1, max_digits=2),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
