# Generated by Django 4.2.13 on 2024-07-03 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("davo", "0006_p_command_sensordata_1_p_command_sensordata_2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="P_command_SensorData_1",
        ),
        migrations.DeleteModel(
            name="P_command_SensorData_2",
        ),
    ]
