# Generated by Django 4.2.13 on 2024-07-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("davo", "0008_onoff_alter_sensordata_1_battery_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata_1",
            name="battery_level",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_1",
            name="electrical_conductivity",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_1",
            name="humidity_25",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_1",
            name="humidity_50",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_1",
            name="humidity_75",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_2",
            name="battery_level",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_2",
            name="electrical_conductivity",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_2",
            name="humidity_25",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_2",
            name="humidity_50",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="sensordata_2",
            name="humidity_75",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
