# Generated by Django 4.2.13 on 2024-07-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("davo", "0009_alter_sensordata_1_battery_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiegoSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(default="10:00")),
                ("duration", models.IntegerField(default=5)),
                ("selected_date", models.DateField()),
            ],
        ),
    ]
